add cluster domain
fluent/fluentbit-operator pull request #170
Opened 2021-11-18 14:53 UTC by wenchajun

Add FluentBit Cluster CRD such as clusterinput.fluentbit.fluent.io while keeping the original namespace crd like Input.logging.kubesphere.io

This is another form of adding a domain
Signed-off-by: chengdehao <dehaocheng@yunify.com>

2021-11-18 15:01 UTC, benjaminhuo commented
> Add FluentBit Cluster CRD such as clusterinput.fluentbit.fluent.io while keeping the original namespace crd like Input.logging.kubesphere.io
> 
> This is another form of adding a domain Signed-off-by: chengdehao [dehaocheng@yunify.com](mailto:dehaocheng@yunify.com)

This PR is similar to https://github.com/fluent/fluentbit-operator/pull/167 ? A better approach to do the same thing?

2021-11-18 15:42 UTC, benjaminhuo commented on pkg/operator/daemonset.go
> +								},
Is it ok to have two config here? 
one local, one cluster？

2021-11-19 02:45 UTC, wenchajun commented
Yes, although this PR implements the same functionality as the original PR, it is implemented in a different way. 
There are three main differences.
- [The secrets of the namespace](https://github.com/fluent/fluentbit-operator/pull/170/files#diff-0b752120e79a0e2d3a24281bbe4463ba6c9b115c9c0db57433160cb32fcf1f51R109-R110) In this PR, cluster-level secret is generated in the namespace to which the operator belongs, not in every namespace. Maybe in the future, you can specify namespaces to generate the corresponding secret?
- [cluster and namespace config](https://github.com/fluent/fluentbit-operator/pull/170/files#diff-402c52300767eca3e94946b162473b45fcf6971a390788a2973b661bbc01c311L1)In the https://github.com/fluent/fluentbit-operator/pull/167,You can bind secret, cluster-fluentbit-config, or Fluentbit-config.like this
![11](https://user-images.githubusercontent.com/39892300/142555887-0ce0fa1e-d88e-4de7-8b8a-c9a96f20e1dc.png)
In this PR, you need to bind namespace-level Config to cluster-level configs, like this
![22](https://user-images.githubusercontent.com/39892300/142556093-2e9b4190-eb36-4aa0-bf81-35da93b80d3e.png)
Frankly speaking, I think both have their advantages and disadvantages. As for the choice, maybe we can discuss it

2021-11-19 02:55 UTC, wenchajun commented on conf/fluent-bit.conf
> +@INCLUDE /fluent-bit/clusterconfig/cluster-fluent-bit.conf
I added a conf

2021-11-19 03:03 UTC, wanjunlei requested changes

2021-11-19 03:03 UTC, wanjunlei commented on controllers/clusterfluentbitconfig_controller.go
> +		scripts, err := cfg.RenderLuaScript(cl, clusterFilters)
The script for cluster Lua filter and namespace Lua filter are in the different directories, how to handle this?

2021-11-19 03:31 UTC, benjaminhuo commented
@wanjunlei @zhu733756 pls help to review this PR and the #167 to decide which method we should use

2022-02-10 12:47 UTC, closed without merging