Add build and push image CI
fluent/fluentbit-operator pull request #213
Opened 2022-02-22 06:38 UTC by zhu733756

Signed-off-by: zhu733756 <zhu733756@kubesphere.io>

Enhance https://github.com/fluent/fluentbit-operator/pull/210

Push images to the org like kubesphere after adding accounts with permissions. Suppose the tag is latest.

- kubepshere/fluentbit-operator:latest with buildx(and64/arm64)
- kubesphere/fluentbit:latest with amd64
- kubesphere/fluentd:latest with amd64

Each pr after merged will push a new image.

/cc @patrick-stephens @benjaminhuo @wanjunlei @wenchajun Pls move here.

2022-02-22 07:51 UTC, zhu733756 commented
See https://github.com/zhu733756/fluentbit-operator/actions/runs/1880252411 and https://github.com/zhu733756/fluentbit-operator/actions/runs/1880252403

2022-02-22 09:13 UTC, wanjunlei requested changes

2022-02-22 09:13 UTC, wanjunlei commented on .github/workflows/build-fb-image.yaml
> +      - name: Setting Environment Variables
This should be deleted.

2022-02-22 09:13 UTC, wanjunlei commented on .github/workflows/build-fd-image.yaml
> +        run: |
This should be deleted.

2022-02-22 09:13 UTC, wanjunlei commented on .github/workflows/build-op-image.yaml
> +    paths:
Need to exclude the directory `pkg/fsnotify`

2022-02-22 10:12 UTC, wanjunlei approved these changes

2022-02-23 02:11 UTC, benjaminhuo approved these changes

2022-02-23 02:11 UTC, merged